version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: binder
      POSTGRES_DB: signature-booth
    ports:
      - "5434:5432"
